
# gencmd_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '1E0349E66FEF050B98C84274B5005B31'
    
_lr_action_items = {'STRING':([0,9,16,18,23,],[2,2,2,2,2,]),'OPTIONNAME':([9,18,],[16,16,]),'PARAM':([0,9,16,18,23,],[1,1,1,1,1,]),'QSTRING':([0,9,16,18,23,],[7,7,7,7,7,]),'NEWLINE':([1,2,3,4,5,6,7,11,12,13,14,16,17,19,20,21,22,25,],[-19,-11,9,-3,-2,-4,-12,-8,18,-7,-10,-13,-9,-14,-18,-16,-17,-15,]),'$end':([8,9,10,15,18,24,],[0,-20,-1,-6,-20,-5,]),'SEPERATER':([16,],[23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'optionarg':([16,23,],[19,25,]),'args':([9,18,],[10,24,]),'string':([0,9,16,18,23,],[4,11,20,11,20,]),'option':([9,18,],[13,13,]),'param':([0,9,16,18,23,],[5,14,21,14,21,]),'empty':([9,18,],[15,15,]),'quotedstring':([0,9,16,18,23,],[6,17,22,17,22,]),'executable':([0,],[3,]),'arg':([9,18,],[12,12,]),'command':([0,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> executable NEWLINE args','command',3,'p_command','gencmd.py',66),
  ('executable -> param','executable',1,'p_executable','gencmd.py',70),
  ('executable -> string','executable',1,'p_executable','gencmd.py',71),
  ('executable -> quotedstring','executable',1,'p_executable','gencmd.py',72),
  ('args -> arg NEWLINE args','args',3,'p_args','gencmd.py',77),
  ('args -> empty','args',1,'p_args_empty','gencmd.py',81),
  ('arg -> option','arg',1,'p_arg','gencmd.py',85),
  ('arg -> string','arg',1,'p_arg','gencmd.py',86),
  ('arg -> quotedstring','arg',1,'p_arg','gencmd.py',87),
  ('arg -> param','arg',1,'p_arg','gencmd.py',88),
  ('string -> STRING','string',1,'p_string','gencmd.py',93),
  ('quotedstring -> QSTRING','quotedstring',1,'p_quotedstring','gencmd.py',97),
  ('option -> OPTIONNAME','option',1,'p_option','gencmd.py',101),
  ('option -> OPTIONNAME optionarg','option',2,'p_option_value','gencmd.py',105),
  ('option -> OPTIONNAME SEPERATER optionarg','option',3,'p_option_sep_value','gencmd.py',109),
  ('optionarg -> param','optionarg',1,'p_optionarg','gencmd.py',113),
  ('optionarg -> quotedstring','optionarg',1,'p_optionarg','gencmd.py',114),
  ('optionarg -> string','optionarg',1,'p_optionarg','gencmd.py',115),
  ('param -> PARAM','param',1,'p_param','gencmd.py',120),
  ('empty -> <empty>','empty',0,'p_empty','gencmd.py',125),
]
